//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDevices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int id { get; set; }
        public string name { get; set; }
        public string order_number { get; set; }
        public string customer_name { get; set; }
        public int count { get; set; }
        public System.DateTime date { get; set; }
        public decimal cost { get; set; }
        public string address { get; set; }
        public int status_id { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
