//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDevices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Devices = new HashSet<Devices>();
            this.Devices1 = new HashSet<Devices>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<bool> can_redact { get; set; }
        public Nullable<bool> can_delete { get; set; }
        public int role_id { get; set; }
        public Nullable<bool> can_add { get; set; }
    
        public virtual ICollection<Devices> Devices { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Devices> Devices1 { get; set; }
    }
}
